language: ruby
rvm:
- 2.2.7
sudo: false
before_script:
- git config --global user.email "bouanto@zoho.com"
- git config --global user.name "Antoni Boucher"
script: bundle exec rake deploy
env:
  global:
  - secure: ZFskiTBhbTN8LSOJ4lQE80KaQw1U0uSWNWKddDWawvWSZTdMzhn2usHmHQPZ524+Ze5aRUBbjpGdVb4+0JdjaYGIUpS+11SWRWhrMdHa081h+JbXLo8yiwf60/ypWvztyjGHlrWNRQghqUR5TMg5k8lOH92maXpatY1f+m5NPiIpXxWXhyOphbwnShmznHDqLvZzfjiGp3QVDcwNxKo06NY+aj5EbA6i8CPRvbScvdSFCINlfRteatw09npfJALWNoiYndInWOvRFh0wtltBZp5gFJkx8OEruIRRvAzfyxk0kuKJvPDrWb/72DvdnTW1luDKT8dPjHzNsafjiHAjdQcMfRrATu6T/kVK0hvRlyWGRCk4FbnQJGLH1ep6Znk0+0oKYa5fdThES0CIh/fkoZ3CYsD2ArSkJ+dGln9MhGp0jZEdUUfcmvR08oP6E6pEm/igQiw7N3J4eaybRvyNZfX55d7/sUEv8j0y2wrmMtg07GKQOvKvgC/hi5MV+6vX7VH5f5TacMmIVdS0J6LZyOxwLiDA561WqFzjhVJbk4QoGY6bVwcJHuva7HWJpYDoS+YqcoxBNBC65Otdh6w3A+WihGtGtHqSkNZMjEb/KjAUF2mPOyrzbVejcUGfZBYHeafsTRyWaw5d1g9tHAPyoOqBdxjOKN0Y4BZ7pgovRIs=
